# Generated by Django 4.2.5 on 2023-10-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_comment'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='favorite_recipes', to='recipe.recipe'),
        ),
    ]
