# Generated by Django 3.2.5 on 2023-09-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('image', models.URLField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('ratings', models.PositiveIntegerField()),
                ('ingredients', models.JSONField()),
                ('steps', models.JSONField()),
                ('nutrients', models.JSONField()),
                ('times', models.JSONField()),
                ('serves', models.PositiveIntegerField()),
                ('difficult', models.CharField(max_length=255)),
                ('vote_count', models.PositiveIntegerField()),
                ('subcategory', models.CharField(max_length=255)),
                ('dish_type', models.CharField(max_length=255)),
                ('maincategory', models.CharField(max_length=255)),
            ],
        ),
    ]
