# Generated by Django 3.2.5 on 2023-09-26 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='ratings',
            new_name='rattings',
        ),
    ]
