# Generated by Django 3.2.5 on 2023-09-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_rename_ratings_recipe_rattings'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dish_type_slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='maincategory_slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='subcategory_slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='url_slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', unique=True),
        ),
    ]
