# Generated by Django 4.2.5 on 2023-10-14 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_remove_recipe_url_remove_recipe_vote_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='times',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/recipe_images'),
        ),
    ]
