# Generated by Django 4.2.5 on 2023-10-14 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_alter_recipe_uploaded_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='uploaded_image',
        ),
    ]
