# Generated by Django 4.2.5 on 2023-10-21 05:46

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0012_recipe_uploaded_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="uploaded_image",
            field=models.ImageField(
                null=True,
                blank=True,
                upload_to=recipe.models.Recipe.generate_slugified_filename,
            ),
        ),
    ]
