# Generated by Django 4.2.5 on 2023-10-21 05:47

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_alter_recipe_name_alter_recipe_uploaded_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to=recipe.models.Recipe.generate_slugified_filename),
        ),
    ]
