# Generated by Django 4.2.5 on 2023-10-23 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_rename_dislike_commentdislike_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentDislike',
        ),
    ]
