# Generated by Django 4.2.5 on 2024-08-12 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_delete_commentdislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='difficult',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='rattings',
        ),
    ]
