# Generated by Django 4.2.5 on 2024-08-12 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_remove_recipe_difficult_remove_recipe_rattings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='comments',
        ),
    ]
